{{- if and .Values.main.enabled .Values.main.secrets.genericOpenAiApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anythingllm.fullname" . }}-secrets
  labels:
    {{- include "anythingllm.labels" . | nindent 4 }}
    app.kubernetes.io/component: main
type: Opaque
data:
  GENERIC_OPEN_AI_API_KEY: {{ .Values.main.secrets.genericOpenAiApiKey | b64enc | quote }}
{{- end }} 