apiVersion: v2
name: llama-vision
description: Llama 3.2 11B Vision - Multimodal chat application with Gradio frontend and TGI backend
type: application
version: 0.0.1
appVersion: "latest"
maintainers:
  - name: Dell
home: https://huggingface.co/meta-llama/Llama-3.2-11B-Vision-Instruct
sources:
  - https://huggingface.co/spaces/huggingface-projects/llama-3.2-vision-11B
keywords:
  - llm
  - vision
  - multimodal
  - gradio
  - llama
  - tgi
