apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName | default "tgi" }}
spec:
  replicas: {{ .Values.numReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName | default "tgi" }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName | default "tgi" }}
    spec:
      nodeSelector: {{ (include "instance" . | fromYaml).nodeSelector | toYaml | nindent 12 }}
      containers:
        - name: {{ .Values.instanceName }}
          {{- if eq (include "instance" . | fromYaml).provider "nvidia" }}
          image: "registry.dell.huggingface.co/enterprise-dell-inference-{{ .Values.modelId | lower | replace "/" "-" }}:latest"
          {{- else if eq (include "instance" . | fromYaml).provider "amd" }}
          image: "registry.dell.huggingface.co/enterprise-dell-inference-{{ .Values.modelId | lower | replace "/" "-" }}-amd:latest"
          securityContext:
            seccompProfile:
              type: Unconfined
          {{- end }}
          resources:
            requests: {{ (include "instance" . | fromYaml).requests | toYaml | nindent 16 }}
            limits: {{ (include "instance" . | fromYaml).limits | toYaml | nindent 16 }}
          env:
            - name: NUM_SHARD
              value: {{ .Values.numGpus | quote }}
            - name: PORT
              value: {{ .Values.port | default (int 80) | quote }}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          {{- if eq (include "instance" . | fromYaml).provider "amd" }}
            - name: dev-kfd
              mountPath: /dev/kfd
            - name: dev-dri
              mountPath: /dev/dri
          {{- end }}
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            {{- if eq (include "instance" . | fromYaml).provider "nvidia" }}
            sizeLimit: 1Gi
            {{- else if eq (include "instance" . | fromYaml).provider "amd" }}
            {{/* NOTE: this is an edge case reported by Dell */}}
            {{- if and (eq (.Values.modelId | lower ) "deepseek-ai/deepseek-r1-distill-llama-70b") (eq .Values.numGpus 4) }}
            sizeLimit: 512Gi
              {{- else }}
            sizeLimit: 256Gi
              {{- end }}
            {{- end }}
        {{- if eq (include "instance" . | fromYaml).provider "amd" }}
        - name: dev-kfd
          hostPath:
            path: /dev/kfd
        - name: dev-dri
          hostPath:
            path: /dev/dri
        {{- end }}
