apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName | default "tgi" }}
  labels:
    {{- include "models.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.env.PORT | default (int 80) }}
      targetPort: {{ .Values.env.PORT | default (int 80) }}
  selector:
    app: {{ .Values.appName | default "tgi" }} 