{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llama-vision.backend.name" . }}-secret
  labels:
    {{- include "llama-vision.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  hf-token: {{ .Values.backend.secrets.hfToken | quote }}
{{- end }}
