apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName | default "tgi" }}
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.port | default (int 80) }}
      targetPort: {{ .Values.port | default (int 80) }}
  selector:
    app: {{ .Values.appName | default "tgi" }}
