apiVersion: v2
name: openwebui
description: OpenWebUI - A modern, feature-rich web UI for Ollama and LLMs
type: application
version: 0.1.0
appVersion: "latest"
maintainers:
  - name: Dell
home: https://github.com/open-webui/open-webui
sources:
  - https://github.com/open-webui/open-webui
icon: https://raw.githubusercontent.com/open-webui/open-webui/main/public/logo.png
keywords:
  - llm
  - ollama
  - openai
  - webui
  - mcp 