apiVersion: v1
kind: Service
metadata:
  name: nemotron-service
spec:
  type: {{ .Values.services.nemotron.type }}
  selector:
    app: nemotron
  ports:
    - protocol: TCP
      port: {{ .Values.services.nemotron.port }}
      targetPort: {{ .Values.services.nemotron.port }}
