{{- if and .Values.main.enabled .Values.main.secrets.openaiApiKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openwebui.fullname" . }}-secrets
  labels:
    {{- include "openwebui.labels" . | nindent 4 }}
    app.kubernetes.io/component: main
type: Opaque
data:
  OPENAI_API_KEYS: {{ .Values.main.secrets.openaiApiKeys | b64enc }}
{{- end }} 