apiVersion: v1
kind: Service
metadata:
  name: embedqa-service
spec:
  type: {{ .Values.services.embedqa.type }}
  selector:
    app: embedqa
  ports:
    - protocol: TCP
      port: {{ .Values.services.embedqa.port }}
      targetPort: {{ .Values.services.embedqa.port }}
