apiVersion: v1
kind: Service
metadata:
  name: llama-instruct-service
spec:
  type: {{ .Values.services.llamaInstruct.type }}
  selector:
    app: llama-instruct
  ports:
    - protocol: TCP
      port: {{ .Values.services.llamaInstruct.port }}
      targetPort: {{ .Values.services.llamaInstruct.port }}
