apiVersion: v1
kind: Secret
metadata:
  name: ngc-api-key
type: Opaque
stringData:
  NGC_API_KEY: {{ .Values.ngcApiKey | quote }}
---

{{- if .Values.registry.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.secretName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\"}}}" .Values.registry.server .Values.registry.username .Values.ngcApiKey .Values.registry.email | b64enc }}

{{- end -}}
