name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.9.0'  # Specify a fixed version instead of 'latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Charts
        run: |
          # Create temp directory for packaged charts
          mkdir -p .cr-release-packages
          
          # Process models chart (directly in charts directory)
          helm package charts/models -d .cr-release-packages
          
          # Process all charts in apps subdirectory
          for chart in charts/apps/*; do
            if [ -d "$chart" ]; then
              echo "Packaging chart: $chart"
              helm package "$chart" -d .cr-release-packages
            fi
          done
          
          # List what was packaged
          ls -la .cr-release-packages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}" 